//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ISimilarityWordsAnalizer 
{
	/// <summary>
    /// Devuelve el nivel de similaridad de dos palabras
    /// </summary>
    /// <param name="wordA"></param>
    /// <param name="wordB"></param>
    /// <returns></returns>
    double getSimilarityWeighing(string wordA, string wordB);

}

