//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ParagraphCleaner : IParagraphCleaner
{
    private HashSet<string> dictionary { get; set; }
    public ParagraphCleaner(HashSet<string> palabrasPorQuitar) {
        dictionary = palabrasPorQuitar;
    }

	public string clean(string input)
	{
        char[] caracteresSeparadores = { ',', ' ', ';', '!', '?', '¿', '¡', '.', ':'};
        string[] wordsArray = input.Split(caracteresSeparadores);//TODO: Mejorar por medio de un replace.
        string result = "";
        foreach (string word in wordsArray) result += word + " ";
        return result;
    }

}

