//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ITrieDictionary  : IContainer
{
	int insert(object String word);

	int remove(object String word);

	void print();

	int search(object String word);

}

