//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SemanticFieldAnalizer
{
	private Map<String,Double> _indexedByField
	{
		get;
		set;
	}

	public virtual ISimilarityWordsAnalizer ISimilarityWordsAnalizer
	{
		get;
		set;
	}

	public virtual IEnumerable<TrieDictionaryFactory> TrieDictionaryFactory
	{
		get;
		set;
	}

	public virtual Exception Exception
	{
		get;
		set;
	}

	public virtual IParagraphCleaner IParagraphCleaner
	{
		get;
		set;
	}

	public SemanticFieldAnalizer(object String targetPath, object String semanticDictionaryPath)
	{
	}

	public virtual Double getIndexByKey(object String key)
	{
		throw new System.NotImplementedException();
	}

	public virtual string getMainField()
	{
		throw new System.NotImplementedException();
	}

	public virtual void toString()
	{
		throw new System.NotImplementedException();
	}

}

