//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrieDictionary : ITrieDictionary
{
	public virtual TrieNode _rootNode
	{
		get;
		set;
	}

	public virtual ITrieNode ITrieNode
	{
		get;
		set;
	}

	public virtual Iterator getIterator()
	{
		throw new System.NotImplementedException();
	}

	public virtual int insert(object String word)
	{
		throw new System.NotImplementedException();
	}

	public virtual int remove(object String word)
	{
		throw new System.NotImplementedException();
	}

	public virtual void print()
	{
		throw new System.NotImplementedException();
	}

	public virtual int search(object String word)
	{
		throw new System.NotImplementedException();
	}

}

