//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrieDictionaryIterator : Iterator
{
	public virtual bool hasNext()
	{
		throw new System.NotImplementedException();
	}

	public virtual string next()
	{
		throw new System.NotImplementedException();
	}

}

