//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrieDictionaryFactory
{
	public virtual ITrieDictionary ISemanticTrieDictionary
	{
		get;
		set;
	}

	public static ITrieDictionary getInstanceByParsing(object String input)
	{
		throw new System.NotImplementedException();
	}

	public static ITrieDictionary getInstance()
	{
		throw new System.NotImplementedException();
	}

}

