//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ITrieNode 
{

	/// <summary>
    /// Asigna un nodo a una letra.
    /// </summary>
    /// <param name="c">Letra</param>
    /// <param name="node">Nodo</param>
    /// <returns></returns>
    int asign(char c, ITrieNode node);


	/// <summary>
    /// Retorna el nodo relacionado a una letra
    /// </summary>
    /// <param name="c"></param>
    /// <returns></returns>
    ITrieNode value(char c);

    /// <summary>
    /// Retorna el nodo padre.
    /// </summary>
    /// <returns></returns>
    ITrieNode getParent();


    /// <summary>
    /// Retorna la cantidad de hijos que tiene el nodo.
    /// </summary>
    /// <returns></returns>
    int getChildrenCount();


	/// <summary>
    /// Termina un nodo para indicar que concluye una palabra.
    /// </summary>
    /// <returns>Retorna 1 si ya estaba terminado y 0 si no.</returns>
    int terminate();


    /// <summary>
    /// Retorna si está terminada una palabra en el nodo actual
    /// </summary>
    /// <returns>1 si sí y 0 si no.</returns>
    int isTerminated();

}

