//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.Collections;
using System.Linq;
using System.Text;

public interface ITrieDictionary  : IEnumerable
{
	int insert(string word);

	int remove(string word);

	void print();

	int search(string word);




}

