//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrieDictionaryFactory
{

	public static ITrieDictionary getInstanceByParsing(string input)
	{
        if ("" == input) throw new ParsingException();
        //Se coloca en una estructura de dictionario
        TrieDictionary dictionary = new TrieDictionary();
        string[] words = input.Split(' ');                          //Se separa mediante espacios
        foreach (string word in words) dictionary.insert(word);
        return dictionary;
	}

	public static ITrieDictionary getInstance()
	{
        return new TrieDictionary();
	}

}

